# Generated by Django 2.2.16 on 2020-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('primary_release_year', models.IntegerField()),
                ('themoviedb_id', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=300)),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('formats', models.ManyToManyField(blank=True, default=None, to='movies.Format')),
            ],
        ),
    ]
