# Generated by Django 2.2.16 on 2020-09-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sort_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
