# Generated by Django 2.2.16 on 2020-09-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_sort_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='sort_title',
        ),
    ]
